Update deploy_nginx.yml

diff --git a/.github/workflows/deploy_nginx.yml b/.github/workflows/deploy_nginx.yml
--- a/.github/workflows/deploy_nginx.yml
+++ b/.github/workflows/deploy_nginx.yml
@@ -36,7 +36,16 @@ jobs:
           
           sudo docker cp /tmp/index.html proxy:/var/www/html/index.html
         EOF
-
+        
+    - name: Get HTTTP Code from Host1
+      run: |  
+        if curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.HOST1_IP }} | grep -q "200"; then
+          echo "Deployment to Host 1 successful!"
+        else
+          echo "Deployment to Host 1 failed!"
+          exit 1
+        fi
+    
     - name: Deploy Nginx to Host 2
       if: success()
       run: |
@@ -54,3 +63,12 @@ jobs:
           
           sudo docker cp /tmp/index.html proxy:/var/www/html/index.html
         EOF
+
+    - name: Get HTTTP Code from Host1
+      run: |  
+        if curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.HOST2_IP }} | grep -q "200"; then
+          echo "Deployment to Host 1 successful!"
+        else
+          echo "Deployment to Host 1 failed!"
+          exit 1
+        fi
